### ISSUE TITLE
CV folds are done twice

### ISSUE THREAD

**Issue by dsevero** [tansey/hrt#1]
Greetings @tansey .

I'm curious to know why you you do cross-validation twice in `hrt/examples/ccle/main.py`.

`fit_cv` [has a loop](https://github.com/tansey/hrt/blob/master/examples/ccle/main.py#L32) that iterates over the `folds` variable (first CV), and it calls `fit_elastic_net_ccle` [which uses](https://github.com/tansey/hrt/blob/master/examples/ccle/main.py#L21-L23) `ElasticNetCV` with `cv=nfolds` (second CV).

**Comment by tansey** [comment]
So there are two different CV uses here. The outer one is for the CV-HRT. The inner one is to select the hyperparameters of elastic net. In that inner loop, we're taking the training data (i.e. all but the k'th fold) and re-splitting it to choose hyperparameters. Those chosen hyperparameters are then used on the held out fold in the outer loop. This is to prevent "double-dipping" into the data; i.e. we wouldn't want to tune our hyperparameters on the same data that we're testing for conditional independence with.

**Comment by dsevero** [comment]
I see, thanks. Any reason not to use multiple processors with `n_jobs` in `ElasticNetCV` ?

**Comment by tansey** [comment]
If I recall correctly, I think that breaks multiprocessing in Python. You can't run multiple independent threads each with multiprocessing sklearn jobs.
